# Generated by Django 2.1.4 on 2018-12-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('Client_Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Client_Name', models.CharField(max_length=50)),
                ('Client_Gstin', models.CharField(max_length=20)),
                ('Client_Address', models.TextField(max_length=500)),
                ('Client_Email', models.EmailField(max_length=254)),
                ('Client_Exist', models.BooleanField(default=True)),
            ],
        ),
    ]
