# Generated by Django 2.1.4 on 2019-02-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Client_Id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
