# Generated by Django 2.1.4 on 2019-03-28 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('Design_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Design_Dimension', models.CharField(max_length=100)),
                ('Design_Connection', models.CharField(max_length=100)),
                ('Design_Fpi', models.CharField(max_length=50)),
                ('Design_Tube', models.CharField(max_length=100)),
                ('Design_Hairpin', models.CharField(max_length=100)),
                ('Design_Drawing', models.FileField(blank=True, null=True, upload_to='')),
                ('Design_Revision', models.CharField(max_length=50)),
                ('Design_Origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
            ],
        ),
    ]
