# Generated by Django 2.1.4 on 2019-03-26 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('design', '0001_initial'),
        ('reservoir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Product_Price', models.CharField(max_length=50)),
                ('Product_Design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.Design')),
                ('Product_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservoir.ProductType')),
            ],
        ),
    ]
