# Generated by Django 2.1.4 on 2019-03-26 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('Drawing_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Drawing_File', models.FileField(upload_to='')),
                ('Drawing_Revision', models.CharField(max_length=10)),
                ('Drawing_Origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
            ],
        ),
    ]
