# Generated by Django 2.1.4 on 2019-03-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('ProductType_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ProductType', models.CharField(max_length=100)),
            ],
        ),
    ]
