# Generated by Django 2.1.4 on 2018-12-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Id', models.CharField(max_length=10)),
                ('User_Name', models.CharField(max_length=32)),
                ('User_Email', models.EmailField(max_length=50)),
                ('User_Role', models.CharField(max_length=32)),
                ('User_Password', models.CharField(max_length=64)),
                ('User_Exist', models.BooleanField(default=True)),
            ],
        ),
    ]
