# Generated by Django 2.1.4 on 2018-12-13 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('Invoice_Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Invoice_Number', models.CharField(max_length=10)),
                ('Invoice_Exist', models.BooleanField(default=True)),
                ('Invoice_Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
            ],
        ),
    ]
