# Generated by Django 2.1.4 on 2019-03-26 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('Invoice_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Invoice_Product', models.CharField(max_length=50)),
                ('Invoice_Total', models.CharField(max_length=50)),
                ('Invoice_Exist', models.BooleanField(default=True)),
                ('Invoice_Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
                ('Invoice_Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
    ]
