# Generated by Django 2.1.4 on 2019-02-15 04:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190201_1456'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='Invoice_Number',
        ),
        migrations.AddField(
            model_name='invoice',
            name='Invoice_Order',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
            preserve_default=False,
        ),
    ]
