# Generated by Django 2.1.4 on 2019-01-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Order_Client_Name', models.CharField(max_length=50)),
                ('Order_Amount', models.CharField(max_length=10)),
            ],
        ),
    ]
