# Generated by Django 2.1.4 on 2019-02-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Order_Id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
